name: publish 
on:
  push:
    branches: 
      - main
  workflow_dispatch:  
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    name: Build and publish Zensical website
    if: github.event.repository.fork == false    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v6
      - name: Checkout repo 
        uses: actions/checkout@v7
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Install Zensical
        run: pip install zensical
        working-directory: src
      - name: Build English docs
        run: zensical build --clean -f en/zensical.toml
        working-directory: src
      - name: Build German docs
        run: zensical build --clean -f de/zensical.toml
        working-directory: src
      - name: Prepare GitHub Pages artifact
        run: |
          mkdir -p publish/en
          mkdir -p publish/de
          cp -R src/en/site/. publish/en/
          cp -R src/de/site/. publish/de/
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: publish
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
        id: deployment
